services:
  postgres:
    image: postgres:17
    container_name: three-tier-postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: artifact_auction_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend

      # command to login through docker desktop to execute sql:
      # psql -U admin -h localhost -d artifact_auction_db -W

volumes:
  postgres-data:

networks:
  backend:
