services:
  postgres:
    image: postgres:18
    container_name: three-tier-postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: artifact_auction_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-datalayer/database:/docker-entrypoint-initdb.d
    networks:
      - postgres_database

      # command to login through docker desktop to execute sql:
      # psql -U admin -h localhost -d artifact_auction_db -W

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres_database

volumes:
  postgres-data:

networks:
  postgres_database:
